#ACTUAL
spring.datasource.url=jdbc:postgresql://10.134.178.155:5432/app_data_db?sslmode=disable

#Testing
#spring.datasource.url=jdbc:postgresql://localhost:55432/app_data_db

spring.datasource.username=app_user
spring.datasource.password=oN0|3>1d5H:*
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional settings
spring.thymeleaf.cache=false
server.port=8080

# Email settings for Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9dc869001@smtp-brevo.com
spring.mail.password=zT3PC5wIrsjgAD9a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# BetterCare gmail: advicebettercare@gmail.com
bettercare.from=BetterCare <advicebettercare@gmail.com>